# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to recieve changes
  repos: |
    jhudsl/ITCR_Documentation_and_Usability
    jhudsl/ITCR_Cancer_Research_Leadership
#ADD NEW REPO HERE following the format above#
  # Files which should be updated
  - source: .github/workflows/
    dest: .github/workflows/
    deleteOrphaned: true
  - source: scripts/
    dest: scripts/
    deleteOrphaned: true
  - source: docker/
    dest: docker/
    deleteOrphaned: true
  - source: .gitignore
    dest: .gitignore
    deleteOrphaned: true
  - source: getting_started.md
    dest: getting_started.md
    deleteOrphaned: true

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  - source: .github/workflows/
  #   dest: .github/workflows/
  #   deleteOrphaned: true
  # - source: scripts/
  #   dest: scripts/
  #   deleteOrphaned: true
  # - source: docker/
  #   dest: docker/
  #   deleteOrphaned: true
  # - source: .gitignore
  #   dest: .gitignore
  #   deleteOrphaned: true
  # - source: getting_started.md
  #   dest: getting_started.md
  #   deleteOrphaned: true 
