# PR Checks
check-quizzes: yes
url-checker: yes
render-preview: yes
style-and-sp-check: no

# Rendering
render-bookdown: yes
render-leanpub: yes
render-coursera: yes

# Docker specific
docker-build-test: yes
