# Formatting Checks (run at pull request)
check-quizzes: yes
url-checker: yes
render-preview: yes
style-and-sp-check: yes

# Rendering
render-bookdown: yes
render-leanpub: yes
render-coursera: yes

# Docker specific
docker-build: yes
 