# PR Checks
check-quizzes: yes
url-checker: yes
render-preview: yes
style-and-sp-check: yes

# Rendering
render-bookdown: yes
render-leanpub: no
render-coursera: no

# Docker specific
docker-build-test: no
