name: Sync jhudsl-robot

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
     container:
       image: r-base
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Get repo list
        id: repo_list
        run: |
          Rscript -e "install.packages('yaml')"
          repo_list=$(Rscript -e "write(yaml::yaml.load_file('.github/sync.yml')$group$repos, stdout())")
          echo "::set-output name=repo_list::$repo_list"
          echo $repo_list

      - uses: google/secrets-sync-action
          with:
            SECRETS: GH_PAT
            REPOSITORIES: ${{ steps.repo_list.outputs.repo_list }}
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
