# Candace Savonen Dec 2021

name: Configure jhudsl robot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Get repo list
        id: repo_list
        run: |
          Rscript -e "install.packages('yaml')"
          repo_list=$(Rscript -e "cat(yaml::yaml.load_file('.github/sync.yml')$group$repos)")
          echo "::set-output name=repo_list::$repo_list"
          echo $repo_list

      - uses: google/secrets-sync-action@master
        name: Do the secret sync
        with:
          SECRETS: GH_PAT
          REPOSITORIES: ${{ steps.repo_list.outputs.repo_list }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
