# Candace Savonen Apr 2021

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview branch
        uses: actions/checkout@v2
        run: git branch -D preview-${{ github.event.pull_request.number }}
