# Candace Savonen Apr 2021

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:

      # This is because if a PR is closed before a render finishes it won't find it.
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash

      # Delete the branch!
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          branches: preview-${{ github.event.pull_request.number }}

      - name: Delete gist
        id: gist
        run: |
          echo ${{ secrets.GH_PAT }} > docker/git_token.txt
          gist_key=${GITHUB_REPOSITORY}_spell_check_${{ github.event.pull_request.number }}
          gist_url=$(Rscript --vanilla scripts/get_the_gist.R \
            --git_pat docker/git_token.txt \
            --gist_key $gist_key \
            --file resources/spell_check_results.tsv \
            --delete)
          rm docker/git_token.txt
