# Candace Savonen Feb 2022

name: Update Github Actions Switches

on:
  push:
    path:
      - config_automation.yml

jobs:
  update-triggers:
    name: Manage GHA
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course_template

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Run GHA switches script
        run: Rscript --vanilla scripts/employ-gha-switches.R

      - name: Commit updated workflows to current branch
        id: commit_it
        run: |
          git add .github/workflows
          git commit -m "Update GitHub Actions"
          git push origin || echo "No changes to commit"
