
# Jan 2022 Candace Savonen

name: Render Leanpub

#---TRIGGER-START---#
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Render Coursera" ]
    branches: [ main, staging ]
    types:
      - completed
#---TRIGGER-END----#

jobs:
  render-leanpub:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/ottr

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"
          
      # Create screenshots
      - name: Run the screenshot creation
        run: |
          chapt_urls=$(Rscript --vanilla scripts/make_screenshots.R \
            --git_pat ${{ secrets.GH_PAT }} \
            --repo $GITHUB_REPOSITORY)

      # We want a fresh run of the renders each time
      - name: Delete old manuscript/
        run: rm -rf manuscript/

      # Run Leanpub rendering
      - name: Run ottr::bookdown_to_embed_leanpub
        run: |
          Rscript -e "ottr::bookdown_to_embed_leanpub( \
            chapt_img_key = 'resources/chapt_screen_images/chapter_urls.tsv', \
            make_book_txt = TRUE)"

      # Commit the rendered leanpub files
      - name: Commit rendered leanpub files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --force manuscript/*
          git commit -m 'Render Leanpub' || echo "No changes to commit"
          git push --force origin main || echo "No changes to push"
