
# This code was originally written by Josh Shapiro and Candace Savonen
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/refinebio-examples/blob/33cdeff66d57f9fe8ee4fcb5156aea4ac2dce07f/.github/workflows/style-and-sp-check.yml#L1

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Render Bookdown and Coursera

# Controls when the action will run. Triggers the workflow on pull request to main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build-all"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # get the full repo
          fetch-depth: 0
          # use github PAT
          token: ${{ secrets.GH_PAT }}

      # Run bookdown rendering
      - name: Run bookdown render
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "bookdown::render_book('index.Rmd')"

##### If you do not wish to host your course on Coursera, you can delete this section #####
      # Run Coursera version
      - name: Run Coursera version of render
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "leanbuild::render_coursera()"

##### End of Coursera rendering section ########################################

      # Commit the rendered bookdown files
      - name: Commit rendered bookdown files to development branch
        run: |
          git checkout -b "preview"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Render bookdown preview' || echo "No changes to commit"
          git push origin preview || echo "No changes to push"

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Re-rendered bookdown from this commit.
            - See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/preview/index.html)
            - See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/preview/index.html)

          repo-token: ${{ secrets.GH_PAT }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
