# Candace Savonen March 2022

name: Run error checker

on:
  workflow_call:
    inputs:
      report_name:
        default: Report
      report_path:
        required: true
        type: string
      script:
        required: true
        type: string
      docker_image:
      fail_threshold: 0
      success_message: "Test passed!"
      fail_message: "Test failed."
      body_includes: spelling_errors
    secrets:
      GH_PAT:
        required: true

jobs:

  run-report:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker_image }}

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

          branch_name='preview-${{ github.event.pull_request.number }}'
          git fetch --all
          git checkout $branch_name
          git merge -s recursive --strategy-option=theirs origin/${{ github.head_ref }} --allow-unrelated-histories
        shell: bash

      - name: Run the report
        id: check_run
        run: |
          results=$(Rscript ${{ inputs.script }})
          echo "::set-output name=results::$results"

      - name: Archive spelling errors
        if: ${{ steps.check_run.outputs.results > ${{ inputs.fail_threshold }} }}
        uses: actions/upload-artifact@v2
        with:
          name: report-results
          path: ${{ inputs.report_path }}

      - name: Commit error report
        run: |
          branch_name='preview-${{ github.event.pull_request.number }}'
          git add --force ${{ inputs.report_path }} || echo "No changes to commit"
          git commit -m 'Add error check file' || echo "No changes to commit"
          git pull --set-upstream origin $branch_name --allow-unrelated-histories --strategy-option=ours
          git push --force origin $branch_name || echo "No changes to commit"

      - name: Build components of the spell check comment
        id: build-components
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          branch_name='preview-${{ github.event.pull_request.number }}'
          error_url=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/$branch_name/${{ inputs.report_path }}
          echo ::set-output name=time::$(date +'%Y-%m-%d')
          echo ::set-output name=commit_id::$GITHUB_SHA
          echo ::set-output name=error_url::$error_url

      # Handle the commenting
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: errors report

      - name: Errors!
        if: ${{ steps.check_run.outputs.results >= ${{ inputs.fail_threshold }} }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ inputs.fail_message }}!
            [Download the error report here.](${{ steps.build-components.outputs.error_url }})
            _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
          edit-mode: replace

      - name: Check results - fail if too many errors
        if: ${{ steps.check_run.outputs.results >= ${{ inputs.fail_threshold }} }}
        run: exit 1

      - name: No errors
        if: ${{ steps.check_run.outputs.results < ${{ inputs.fail_threshold }} }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ inputs.success_message }}! :tada:
            _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
          edit-mode: replace
