# Candace Savonen March 2022

# This calls the report makers but then also handles the commenting

name: Run error checker

on:
  workflow_call:
    inputs:
      check_type:
        required: true
        type: string
      error_min:
        default: 0
        type: number
      gh_pat:
        type: string
        required: true

jobs:
  error-check:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course_template:main

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Make branch if it doesn't exist
      run: |
        git config --local user.email "itcrtrainingnetwork@gmail.com"
        git config --local user.name "jhudsl-robot"

        branch_name='preview-${{ github.event.pull_request.number }}'
        exists=$(git ls-remote https://${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY $branch_name | wc -l | xargs)
        if [[ $exists == 0 ]];then
          echo branch doesnt exist
          git checkout -b $branch_name || echo branch exists
          git push --set-upstream origin $branch_name
        else
          echo branch does exist
        fi
      shell: bash

    - name: Run the check
      uses: jhudsl/ottr-reports@main
      id: check_results
      with:
        check_type: ${{ inputs.check_type }}
        error_min: ${{ inputs.error_min }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.check_results.outputs.error_name }}
        path: ${{ steps.check_results.outputs.report_path }}

############################# Handle commenting ################################

    - name: Build components of the spell check comment
      id: build-components
      run: |
        echo ::set-output name=time::$(date +'%Y-%m-%d')
        echo ::set-output name=commit_id::$inputs.commit_id
        echo ::set-output name=error_url::$error_url
      shell: bash

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ steps.check_results.outputs.error_name }}

    - name: There are errors!
      if: ${{ steps.check_results.outputs.error_num >= inputs.error_min }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :warning: ${{ steps.check_results.outputs.error_name }} :warning:
          There are ${{ steps.check_results.outputs.error_name }} that need to be addressed. [Read this guide for more info](https://github.com/jhudsl/OTTR_Template/wiki/Most-common-errors-and-pitfalls#spell-checkurl-checkquiz-format-fail).
          [Download the errors here.](${{ steps.build-components.outputs.error_url }})
          _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
        edit-mode: replace

    - name: Fail if too many errors
      if: ${{ steps.check_results.outputs.error_num >= inputs.error_min }}
      run: exit 1
      shell: bash

    - name: No errors
      if: ${{ steps.check_results.outputs.error_num < inputs.error_min }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          No ${{ steps.check_results.outputs.error_name }}! :tada:
          _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
        edit-mode: replace
