
# This code was originally written by Josh Shapiro and Candace Savonen
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/refinebio-examples/blob/33cdeff66d57f9fe8ee4fcb5156aea4ac2dce07f/.github/workflows/style-and-sp-check.yml#L1

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Style and spell check R markdowns

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "style and check"
  style-n-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        # What branch to commit to: the one from the pull request
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install packages
        run: Rscript -e "install.packages(c('styler', 'spelling'))"

      - name: Run spell check
        id: spell_check_run
        run: |
          results=$(Rscript "scripts/spell-check.R")
          echo "::set-output name=sp_chk_results::$results"
          cat spell_check_results.tsv

      - name: Archive spelling errors
        uses: actions/upload-artifact@v2
        with:
          name: spell-check-results
          path: spell_check_results.tsv

      ############ The items if there's too many spelling errors!
      - name: Build components of the spell check comment
        if: ${{ steps.spell_check_run.outputs.sp_chk_results > 3 }}
        id: build-components
        run: |
          echo ::set-output name=time::$(date +'%Y-%m-%d')
          echo ::set-output name=commit_id::$GITHUB_SHA

      - name: Comment with spelling errors file
        if: ${{ steps.spell_check_run.outputs.sp_chk_results > 3 }}
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
            prefix: :warning: There are spelling errors. Download this file to see them.
            suffix: |
             [Read more about spell check here](https://github.com/jhudsl/OTTR_Template/wiki/Spell-check).

              _Comment as of ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_

            format: name
            addTo: pullandissues

      - name: Check spell check results - fail if too many errors
        if: ${{ steps.spell_check_run.outputs.sp_chk_results > 3 }}
        run: exit 1

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: latest commit

      - name: No spelling errors
        if: ${{ steps.spell_check_run.outputs.sp_chk_results < 3 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            No spelling errors! :tada:
            _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
          edit-mode: replace

      - name: Run styler
        run: Rscript -e "styler::style_file(list.files(pattern = 'Rmd$', recursive = TRUE, full.names = TRUE));warnings()"

      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add \*.Rmd
          git commit -m 'Style Rmds' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
