# This code was originally written by Josh Shapiro
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/exercise-notebook-answers

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Copy files from Bookdown to Leanpub repo
# Copy rendered notebooks to Leanpub repo

# This workflow will run when there are changes to docs/ files in THIS repo
on:
  workflow_dispatch:
  # Only run after the render finishes running
  #workflow_run:
  #  workflows: [ "Build, Render, and Push" ]
  #  branches: [ main ]
  #  types:
  #    - completed

jobs:
  file-bookdown-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Leanpub repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/DaSL_Course_Template_Leanpub
          token: ${{ secrets.GIT_TOKEN }}

      - name: Get docs/ from Bookdown repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          sudo apt-get install subversion

          if [ -d "docs/" ]
          then
          # remove old docs/ files and folder
          rm -r docs/*
          fi

          # Copy over book.bib file
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/book.bib

          # Copy over _bookdown.yml
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/_bookdown.yml

          # Get list of Rmds needing to copy
          rmd_list=$(find . -name '*.Rmd'  | grep '.Rmd')

          for path in $rmd_list
          do
            # test that the path is to an Rmd file, error if not
            [[ $path != *.Rmd ]] && echo "'$path' is not an .Rmd file." && exit 1
            echo $path
            svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/manuscript/${path}
          done

      - name: Create PR with rendered docs files
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Copy docs/ files from Bookdown repository
          signoff: false
          branch: auto_copy_rendered_files
          delete-branch: true
          title: 'GHA: Automated transfer of docs/ from Bookdown repository'
          body: |
            ### Description:
            This PR auto-generated from github actions
              - Copy the bookdown rendered files in docs/ from Bookdown repository
          labels: |
            automated
          reviewers: $GITHUB_ACTOR

      # Write out PR info
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
