# This code was originally written by Josh Shapiro
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/exercise-notebook-answers

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Copy docs/* folder from Bookdown to Leanpub repo
# Copy rendered notebooks to Leanpub repo

# This workflow will run when there are changes to docs/ files in THIS repo
on:
  push:
    branches: [ master, cansavvy/transfer-docs-gha]
    # trigger on changes to exercise notebooks, but not `solved` notebooks
    paths:
     - 'docs/*'

jobs:
  file-bookdown-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Leanpub repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/ITCR_Course_Template_Leanpub
          token: ${{ secrets.TOKEN }}

      - name: Get docs/ from Bookdown repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          # the url from this repo where files will be downloaded from
          base_url=https://${GH_TOKEN}@raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/heads/}
          # urls for
          list_url=(ls -R ${base_url}/docs/*)
          echo $list_url

          # get the file list
          file_paths=$(curl --fail -s ${list_url}) || echo "Error getting docs/ file at ${list_url}"

          # error if the docs/ is empty
          [[ -z $exercise_paths ]] && echo "docs/ folder is empty." && exit 1

          # remove old docs/ files
          rm docs/*

          # get new exercise files and put them in the right place
          for path in $file_paths
          do
            # test that the path is to an md file, error if not
            [[ $path != *.md ]] && echo "'$path' is not an .md file." && exit 1
            echo $path
            curl --fail -s ${base_url}/${path} > ${path}
          done

      - name: Create PR with rendered docs files
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Copy docs/ files from Bookdown repository
          signoff: false
          branch: auto_copy_rendered_files
          delete-branch: true
          title: 'GHA: Automated transfer of docs/ from Bookdown repository'
          body: |
            ### Description:
            This PR auto-generated from github actions
              - Copy the bookdown rendered files in docs/ from Bookdown repository
          labels: |
            automated
          reviewers: $GITHUB_ACTOR

      # Write out PR info
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
