# Adapted from https://github.com/marketplace/actions/url-checker by Candace Savonen

# This github actions tests URLs in the Rmd files, README, and CONTRIBUTING.md
name: Check URLs

# This will be run upon PRs to main
on:
  pull_request:
    branches: [ main ]

# Here's the main action of checking URLs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Rmd file names
        id: get_rmds
        run: |
          rmd_files=$(find . -type f -name '*.Rmd')
          echo "::set-output name=rmd_files::$rmd_files"
          cat rmd_files

      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md,CONTRIBUTING.md, $rmd_files"
